# Generated by Django 2.1.3 on 2018-12-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choic',
            new_name='Choice',
        ),
    ]
